### ISSUE TITLE
[Bug]Timer without cancel

### ISSUE THREAD

**Issue by NaturalSelect** [Mohist-Community/XenforoLogin#9]
https://github.com/Mohist-Community/XenforoLogin/blob/edc098d5a38411358550de953f4dc14bcbcd12be/XenforoLogin-Core/src/main/java/red/mohist/xenforologin/core/utils/LoginTicker.java#L31

**Comment by ishland** [comment]
https://github.com/Mohist-Community/XenforoLogin/blob/edc098d5a38411358550de953f4dc14bcbcd12be/XenforoLogin-Core/src/main/java/red/mohist/xenforologin/core/utils/LoginTicker.java#L42

I did cancel here

**Comment by NaturalSelect** [comment]
You just canel the task
